/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controled.DichVuDAO;
import Controled.PhieuDichVuDAO;
import Model.DichVu;
import Model.PhieuDichVu;
import Model.Phong;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class GDPhieuDichVu extends javax.swing.JFrame {

    /**
     * Creates new form GDPhieuThue
     */
    private ArrayList<DichVu> dsDichVu;
    private ArrayList<PhieuDichVu> dsPhieuDichVuTK;
    
    private DefaultTableModel tblDichVuMD;
    private DefaultTableModel tblPhieuDichVuMD;
    
    private int selectedrowDV;
    private int selectedrowPDV;
    
    
    public GDPhieuDichVu() {
        initComponents();
        this.setTitle("Giao diện phiếu dịch vụ");
        this.setLocationRelativeTo(null);
        ButtonGroup bt = new ButtonGroup();
        bt.add(rbtDaDong);
        bt.add(rbtChuaDong);
        
        dsDichVu = new DichVuDAO().getListDichVu();
        
        tblDichVuMD = (DefaultTableModel) tblDichVu.getModel();
        tblPhieuDichVuMD = (DefaultTableModel) tblPhieuDichVu.getModel();
        
        showDV();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaHDDV = new javax.swing.JTextField();
        txtMaP = new javax.swing.JTextField();
        txtMaDV = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        txtNgaySuDung = new javax.swing.JTextField();
        btnThemPDV = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        rbtDaDong = new javax.swing.JRadioButton();
        rbtChuaDong = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhieuDichVu = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDichVu = new javax.swing.JTable();
        btnaddDVtoPDV = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnCapNhatPDV = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MaHDDV");

        jLabel2.setText("MaP");

        jLabel3.setText("MaDV");

        jLabel4.setText("SoLuong");

        jLabel5.setText("NgaySuDung");

        btnThemPDV.setText("Thêm PDV");
        btnThemPDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemPDVActionPerformed(evt);
            }
        });

        jLabel6.setText("TrangThai");

        rbtDaDong.setText("Đã đóng");

        rbtChuaDong.setSelected(true);
        rbtChuaDong.setText("Chưa đóng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThemPDV)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtMaHDDV, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(txtMaP)
                                .addComponent(txtMaDV)
                                .addComponent(txtSoLuong)
                                .addComponent(txtNgaySuDung))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(rbtDaDong, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtChuaDong)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaHDDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtMaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMaDV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNgaySuDung, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rbtDaDong)
                    .addComponent(rbtChuaDong))
                .addGap(15, 15, 15)
                .addComponent(btnThemPDV)
                .addContainerGap())
        );

        tblPhieuDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MaHDDV", "MaDV", "MaP", "SoLuong", "NgaySuDung", "TrangThai"
            }
        ));
        jScrollPane1.setViewportView(tblPhieuDichVu);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        tblDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MaDV", "TenDV", "DonGia"
            }
        ));
        jScrollPane2.setViewportView(tblDichVu);

        btnaddDVtoPDV.setText("Thêm vào PDV");
        btnaddDVtoPDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddDVtoPDVActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCapNhatPDV.setText("Cập nhật số lượng dịch vụ");
        btnCapNhatPDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatPDVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnaddDVtoPDV)
                        .addGap(71, 71, 71)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnCapNhatPDV)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addComponent(btnBack)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCapNhatPDV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btnaddDVtoPDV)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new GDTrangChu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnaddDVtoPDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddDVtoPDVActionPerformed
        // TODO add your handling code here:
        selectedrowDV = tblDichVu.getSelectedRow();
        if(selectedrowDV == -1){
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn dịch vụ rồi thao tác");
        }
        else if(dsDichVu.size()==0) {
            JOptionPane.showMessageDialog(rootPane, "yêu cầu thêm dịch vụ");
        }
        else{
            DichVu dv = dsDichVu.get(selectedrowDV);
            txtMaDV.setText(dv.getMaDV());
        }
    }//GEN-LAST:event_btnaddDVtoPDVActionPerformed

    private void btnThemPDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemPDVActionPerformed
        // TODO add your handling code here:
        PhieuDichVu pdv = new PhieuDichVu();
        pdv.setMaHDDV(txtMaHDDV.getText());
        pdv.setMaP(Integer.parseInt(txtMaP.getText()));
        pdv.setMaDV(txtMaDV.getText());
        pdv.setSoLuong(Integer.parseInt(txtSoLuong.getText()));
        try {
            pdv.setNgaySuDung(new SimpleDateFormat("dd/MM/yyyy").parse(txtNgaySuDung.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(GDPhieuDichVu.class.getName()).log(Level.SEVERE, null, ex);
        }
        String tt = "chưa đóng";
        if(rbtChuaDong.isSelected()) tt = "chưa đóng";
        if(rbtDaDong.isSelected()) tt = "đã đóng";
        pdv.setTrangThai(tt);
        if(new PhieuDichVuDAO().addPhieuDichVu(pdv)){
            themPDV(pdv);
            JOptionPane.showMessageDialog(rootPane, "Thêm phiếu dịch vụ thành công");
            new GDTrangChu().ThemPDV(pdv);
        }else JOptionPane.showMessageDialog(rootPane, "Dịch vụ này đã có trên phiếu dịch vụ -> yêu cầu cập nhật hoặc chọn dịch vụ khác");
        
            
        
        
    }//GEN-LAST:event_btnThemPDVActionPerformed

    private void btnCapNhatPDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatPDVActionPerformed
        // TODO add your handling code here:
        selectedrowPDV = tblPhieuDichVu.getSelectedRow();
        if(selectedrowPDV == -1){
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn phiếu dịch vụ rồi thao tác");
        }
        else if(dsPhieuDichVuTK.size()==0) {
            JOptionPane.showMessageDialog(rootPane, "yêu cầu thêm phiếu dịch vụ");
        }
        else{
            GDCapNhatPDV GDCNPDV = new GDCapNhatPDV(this, rootPaneCheckingEnabled);
            GDCNPDV.seteditPDV(dsPhieuDichVuTK.get(selectedrowPDV));
            GDCNPDV.setVisible(true);
        }
    }//GEN-LAST:event_btnCapNhatPDVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GDPhieuDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GDPhieuDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GDPhieuDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GDPhieuDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GDPhieuDichVu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCapNhatPDV;
    private javax.swing.JButton btnThemPDV;
    private javax.swing.JButton btnaddDVtoPDV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbtChuaDong;
    private javax.swing.JRadioButton rbtDaDong;
    private javax.swing.JTable tblDichVu;
    private javax.swing.JTable tblPhieuDichVu;
    private javax.swing.JTextField txtMaDV;
    private javax.swing.JTextField txtMaHDDV;
    private javax.swing.JTextField txtMaP;
    private javax.swing.JTextField txtNgaySuDung;
    private javax.swing.JTextField txtSoLuong;
    // End of variables declaration//GEN-END:variables

    void editPDV(Phong p) {
        dsPhieuDichVuTK = new PhieuDichVuDAO().getListPDVTK(p);
        if(dsPhieuDichVuTK.size() > 0){
            showPDVTK();
            txtMaP.setText(p.getMaP()+"");
            txtMaHDDV.setText(dsPhieuDichVuTK.get(0).getMaHDDV());
            txtMaP.setEditable(false);
            txtMaHDDV.setEditable(false);
        }
    }
    
    void themPDV(PhieuDichVu pdv){
        dsPhieuDichVuTK.add(pdv);
        tblPhieuDichVuMD.setRowCount(0);
        for(PhieuDichVu Pdv : dsPhieuDichVuTK){
        tblPhieuDichVuMD.addRow(new Object[]{Pdv.getMaHDDV(), Pdv.getMaDV(), Pdv.getMaP(), 
            Pdv.getSoLuong(), Pdv.getNgaySuDung(), Pdv.getTrangThai()});
        } 
    }
    
    void showPDVTK(){
        for(PhieuDichVu pdv : dsPhieuDichVuTK){
            tblPhieuDichVuMD.addRow(new Object[]{pdv.getMaHDDV(), pdv.getMaDV(), pdv.getMaP(), 
                pdv.getSoLuong(), pdv.getNgaySuDung(), pdv.getTrangThai()});
        }
    }

    void showDV(){
        for(DichVu dv : dsDichVu){
            tblDichVuMD.addRow(new Object[]{dv.getMaDV(), dv.getTenDV(), dv.getDonGia()});
        }
    }

    public void updatePDV(PhieuDichVu pdv) {
//        PhieuDichVu beforPDV = dsPhieuDichVuTK.get(selectedrowPDV);
        dsPhieuDichVuTK.remove(selectedrowPDV);
        themPDV(pdv);
    }


    
}
